// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RenzoAgostini.Server.Data;

#nullable disable

namespace RenzoAgostini.Server.Migrations
{
    [DbContext(typeof(RenzoAgostiniDbContext))]
    [Migration("20250901183158_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("RenzoAgostini.Server.Entities.Painting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medium")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Paintings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Serie marina. Colori caldi.",
                            IsForSale = true,
                            Medium = "Olio su tela",
                            Price = 1200m,
                            Slug = "alba-sul-mare",
                            Title = "Alba sul mare",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            Description = "Acrilico, toni blu.",
                            IsForSale = false,
                            Medium = "Acrilico su tavola",
                            Slug = "notturno",
                            Title = "Notturno",
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            Description = "Paesaggio primaverile.",
                            IsForSale = true,
                            Medium = "Olio su tela",
                            Price = 900m,
                            Slug = "colline",
                            Title = "Colline",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("RenzoAgostini.Server.Entities.Painting", b =>
                {
                    b.OwnsMany("RenzoAgostini.Server.Entities.PaintingImage", "Images", b1 =>
                        {
                            b1.Property<int>("PaintingId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Url")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Height")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Width")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PaintingId", "Url");

                            b1.ToTable("PaintingImages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaintingId");

                            b1.HasData(
                                new
                                {
                                    PaintingId = 1,
                                    Url = "/img/q1a.jpg",
                                    Height = 600,
                                    IsPrimary = true,
                                    Width = 800
                                },
                                new
                                {
                                    PaintingId = 1,
                                    Url = "/img/q1b.jpg",
                                    Height = 600,
                                    IsPrimary = false,
                                    Width = 800
                                },
                                new
                                {
                                    PaintingId = 2,
                                    Url = "/img/q2a.jpg",
                                    Height = 600,
                                    IsPrimary = true,
                                    Width = 800
                                },
                                new
                                {
                                    PaintingId = 2,
                                    Url = "/img/q2b.jpg",
                                    Height = 600,
                                    IsPrimary = false,
                                    Width = 800
                                },
                                new
                                {
                                    PaintingId = 3,
                                    Url = "/img/q3a.jpg",
                                    Height = 600,
                                    IsPrimary = true,
                                    Width = 800
                                });
                        });

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
