version: "3.8"
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: local.test
    env_file: .env.local
    ports:
      - "2525:587"
    volumes:
      - ./config/:/tmp/docker-mailserver/
      - ./data/:/var/mail/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped